---
title: "Named Entity Recognition of regex-cleaned chunks with NAMETAG model (via API)"
---

## Load necessary packages
```{r include=FALSE}
# Package names
packages <- c("dplyr")

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Packages loading
invisible(lapply(packages, library, character.only = TRUE))

```

## Using RStudio jobs to parallelize 
```{r}
# Set up parameters for this job
ner_period <- "*"
ner_exclude <- FALSE

already_ner_processed <-
  list.files(
    path = file.path("data"),
    pattern = "*.rds",
    full.names = TRUE
  ) %>% basename()

# Identify dataset chunks of interest
all_chunks_path_ner <- list.files(path = file.path("../../2.data_transformations", "data", "regex_processed"),
                              pattern = "*.rds",
                              full.names = TRUE) %>%
                              .[grep(pattern = ner_period, ., invert = ner_exclude)]

# Filter for already existing files
all_chunks_path_ner <- file.path("../../2.data_transformations", "data", "regex_processed", setdiff(basename(all_chunks_path_ner), gsub("udpipe_", "", already_ner_processed, fixed = TRUE)))

# Run the script as a RStudio job
rstudioapi::jobRunScript(path = "ner_rstudio_jobs.R", importEnv = TRUE)
```

